version: "3.8"
services:
  web:
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=counter_db
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
