version: "3.8"
services:
  web:
    build:
      context: .
    command: >
      sh -c "python main.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_NAME=counter_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=counter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
